# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlexaHandler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
    ]
