# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlexaHandler', '0002_remove_person_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlexaHandler.Person')),
            ],
        ),
    ]
