# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlexaHandler', '0003_filelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filelist',
            old_name='name',
            new_name='person',
        ),
    ]
