# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlexaHandler', '0004_auto_20170313_1441'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileList',
            new_name='File',
        ),
    ]
