# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlexaHandler', '0005_auto_20170313_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SessID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SessionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.FilePathField(allow_folders=True, path=b'/home/alexa_server/Desktop/Alexa_server/storage', recursive=True)),
                ('Sess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlexaHandler.ClientSession')),
            ],
        ),
        migrations.CreateModel(
            name='SessionVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VarName', models.CharField(max_length=1000)),
                ('VarType', models.CharField(max_length=1000)),
                ('Sess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlexaHandler.ClientSession')),
            ],
        ),
        migrations.CreateModel(
            name='SessionVarFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VarName', models.CharField(max_length=1000)),
                ('Sess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlexaHandler.ClientSession')),
                ('varFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlexaHandler.SessionFile')),
            ],
        ),
    ]
