# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlexaHandler', '0009_remove_nodeflow_nodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsession',
            name='NodeFlows',
        ),
        migrations.RemoveField(
            model_name='clientsession',
            name='varNames',
        ),
    ]
