# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlexaHandler', '0010_auto_20170329_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsession',
            name='varNames',
            field=models.ManyToManyField(to='AlexaHandler.SessionVar'),
        ),
    ]
