# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlexaHandler', '0012_remove_clientsession_varnames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='NodeFlow',
            new_name='Flow',
        ),
    ]
