# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlexaHandler', '0013_auto_20170330_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='Sess',
        ),
    ]
