# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlexaHandler', '0014_remove_node_sess'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='Vars',
            field=models.ManyToManyField(blank=True, to='AlexaHandler.SessionVar'),
        ),
    ]
