# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlexaHandler', '0016_auto_20170410_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockmodel',
            name='Sess',
        ),
        migrations.AlterField(
            model_name='blockchainmodel',
            name='Sess',
            field=models.CharField(max_length=1000),
        ),
    ]
