# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlexaHandler', '0017_auto_20170410_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainmodel',
            name='pickle',
            field=models.FilePathField(path=b'cache/', recursive=True),
        ),
    ]
