# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlexaHandler', '0018_auto_20170410_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchainmodel',
            name='pickle',
        ),
    ]
