# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlexaHandler', '0019_remove_blockchainmodel_pickle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheTable',
            fields=[
                ('cache_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('expires', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'cache_table',
            },
        ),
    ]
